apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-proxy
  namespace: kube-system
spec:
  template:
    spec:
      containers:
      - name: kube-proxy
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
          requests:
            memory: "256Mi"
            cpu: "100m"
        # 关键修复：设置更高的文件描述符限制
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_RESOURCE"]
        # 添加环境变量来控制资源使用
        env:
        - name: GOGC
          value: "50"  # 减少 GC 压力
        - name: GOMAXPROCS
          value: "2"
        # 使用 ulimit 增加文件描述符限制
        command:
        - /bin/sh
        - -c
        - |
          # 设置文件描述符限制
          ulimit -n 65536
          # 启动 kube-proxy
          exec /usr/local/bin/kube-proxy \
            --config=/var/lib/kube-proxy/config.conf \
            --hostname-override=$(NODE_NAME) \
            --v=2