kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  - |
    kind: KubeletConfiguration
    maxOpenFiles: 1048576
  - |
    kind: KubeProxyConfiguration
    conntrack:
      maxPerCore: 0
      min: 65536
      tcpEstablishedTimeout: 24h0m0s
      tcpCloseWaitTimeout: 1h0m0s
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
networking:
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/16"